configs:
    - configs/base.yaml # default arguments for the whole codebase
    - configs/models/wsgs.yaml # model configuration
    - configs/datasets/water_synthetic/swimming_pool_clear.yaml # dataset usage configuration

model_cfg:
    supervisor_cfg:
        perc_loss_start_iter: 45000 # less iterations for faster training

runner_cfg:
    epochs: 140 #120

# prettier-ignore
exp_name: {{fileBasenameNoExtension}}
