configs: configs/datasets/water_synthetic/wsgs.yaml

dataloader_cfg:
    dataset_cfg: &dataset_cfg
        ratio: 0.5
        data_root: data/datasets/water_synthetic/swimming_pool_clear
        view_sample: [0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 
                    50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 
                    100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130, 132, 134, 136, 138, 
                    140, 142, 144, 146, 148, 150, 152, 154, 156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 
                    180, 182, 184, 186, 188, 190, 192, 194, 196, 198, 200, 202, 204, 206, 208, 210, 212, 214, 216, 218, 
                    220, 222, 224, 226, 228, 230, 232, 234, 236, 238, 240, 242, 244, 246, 248, 250, 252, 254, 256, 258, 
                    260, 262, 264, 266, 268, 270, 272, 274, 276, 278, 280, 282, 284, 286, 288, 290, 292, 294, 296, 298, 
                    300]
val_dataloader_cfg:
    dataset_cfg:
        <<: *dataset_cfg
        view_sample: [1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 
                    53, 55, 57, 59, 61, 63, 65, 67, 69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99, 101, 
                    103, 105, 107, 109, 111, 113, 115, 117, 119, 121, 123, 125, 127, 129, 131, 133, 135, 137, 139, 141, 
                    143, 145, 147, 149, 151, 153, 155, 157, 159, 161, 163, 165, 167, 169, 171, 173, 175, 177, 179, 181, 
                    183, 185, 187, 189, 191, 193, 195, 197, 199, 201, 203, 205, 207, 209, 211, 213, 215, 217, 219, 221, 
                    223, 225, 227, 229, 231, 233, 235, 237, 239, 241, 243, 245, 247, 249, 251, 253, 255, 257, 259, 261, 
                    263, 265, 267, 269, 271, 273, 275, 277, 279, 281, 283, 285, 287, 289, 291, 293, 295, 297, 299, 301]
model_cfg:
    sampler_cfg:
        preload_gs: data/datasets/water_synthetic/swimming_pool_clear/sparse/0/points3D.ply
        spatial_scale: 4.255170508218657
        # Reflected Gaussian & Refracted Gaussian
        env_preload_gs: data/datasets/water_synthetic/swimming_pool_clear/envs/points3D.ply
        env_bounds: [[-4.829454755357718, -1.069744836944627, -6.357057040797786], [4.63270209614417, 2.0704181114059796, 4.108605373619256]]
        refracted_preload_gs: data/datasets/water_synthetic/swimming_pool_clear/refracted/points3D.ply
        refracted_bounds: [[-4.829454755357718, -1.069744836944627, -6.357057040797786], [4.63270209614417, 2.0704181114059796, 4.108605373619256]]
        white_bg: False
        initial_plane_offset: -1.21669419
        initial_plane_normal: [0.000995254, -0.998049, 0] # used for water plane init