configs:
    - configs/base.yaml # default arguments for the whole codebase
    - configs/models/wsgs.yaml # model configuration
    - configs/datasets/water_real/bucket_v02.yaml # dataset usage configuration

model_cfg:
    supervisor_cfg:
        perc_loss_start_iter: 45000 # less iterations for faster training
    sampler_cfg:
        max_gs: 2000000
runner_cfg:
    epochs: 140 #140
    

# prettier-ignore
exp_name: {{fileBasenameNoExtension}}
